
<Style>:

    MDScreenManager:
        id:mn 
        MDScreen:
            name:'main'
            MDFlatButton:
                text:'Start Search'
                font_size:21
                pos_hint: {'center_x': 0.5,'center_y': 0.5}
                size_hint: 0.3, 0.2
                md_bg_color: [0,0.5,0.5,1]
                on_press:root.search()
# # ////////FAKE///////
#         MDScreen:
#             name:'fake'
